webtalk_init -webtalk_dir C:\\Studienarbeit_Final\\Final_Design\\Final_Design.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-06-29 15:15:34" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211431583_0_0_948" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "84lq44pk1frrh0ettp0i9fnd0o" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.4_31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU         660  @ 3.33GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3343 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1530276992791" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key hwid -value "1530178478901" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key bspid -value "1530182795946" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key os -value "freertos823_xilinx" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key apptemplate -value "freertos_hello_world" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key projSize -value "483.2265625" -context "sdk\\\\application/1530276992791"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1530278133981"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1530278133981"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1530278133981"
webtalk_add_data -client sdk -key DebugCount -value "7" -context "sdk\\\\bsp/1530278133981"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1530278133981"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1530278133981"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1530278133981"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1530278133981"
webtalk_transmit -clientid 3584167404 -regid "211431583_0_0_948" -xml C:\\Studienarbeit_Final\\Final_Design\\Final_Design.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Studienarbeit_Final\\Final_Design\\Final_Design.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Studienarbeit_Final\\Final_Design\\Final_Design.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
